### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by taetcheson** [pawitp/nexus-5x-blod-fix#1]
I get the following error output with Android factory image bullhead-opm3.171019.016-factory-6e4c89cb.zip:

`$ python ../../nexus-5x-blod-fix-master/disable_cpu_cores.py --disable-encryption ./bootloader-bullhead-bhz31b.img new_boot.img`
`Traceback (most recent call last):
  File "../../nexus-5x-blod-fix-master/disable_cpu_cores.py", line 131, in <module>
    main()
  File "../../nexus-5x-blod-fix-master/disable_cpu_cores.py", line 69, in main
    image_struct = '<%ds%ds%ds%ds' % (header.page_size, pad_size(header.kernel_size), pad_size(header.ramdisk_size), pad_size(header.second_size))
  File "../../nexus-5x-blod-fix-master/disable_cpu_cores.py", line 67, in pad_size
    return ((original_size + header.page_size - 1) // header.page_size) * header.page_size
ZeroDivisionError: integer division or modulo by zero`

What could I be doing wrong?

**Comment by pawitp** [comment]
You need to patch the boot image (boot.img) not the bootloader image.

**Comment by taetcheson** [comment]
Thanks.
